[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Variables d'environnement pour Railway
PORT = "8080"
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:your-app-key-here"
APP_URL = "https://your-app.railway.app"

# Base de données (Railway PostgreSQL)
DB_CONNECTION = "pgsql"
DB_HOST = "${{PGHOST}}"
DB_PORT = "${{PGPORT}}"
DB_DATABASE = "${{PGDATABASE}}"
DB_USERNAME = "${{PGUSER}}"
DB_PASSWORD = "${{PGPASSWORD}}"

# Cache et sessions (Railway Redis)
CACHE_DRIVER = "redis"
SESSION_DRIVER = "redis"
REDIS_HOST = "${{REDISHOST}}"
REDIS_PASSWORD = "${{REDISPASSWORD}}"
REDIS_PORT = "${{REDISPORT}}"

# Mail (utiliser un service externe comme Mailgun, SendGrid, etc.)
MAIL_MAILER = "smtp"
MAIL_HOST = "smtp.mailgun.org"
MAIL_PORT = "587"
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
MAIL_ENCRYPTION = "tls"

# Logging
LOG_CHANNEL = "stack"
LOG_DEPRECATIONS_CHANNEL = "null"
LOG_LEVEL = "error"

[healthcheck]
path = "/health"
